### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by alexcoder04** [alexcoder04/LeoConsole-apkg#3]
## What will be done in the next time

 - [ ] fix compiler warnings
 - [x] save repo databases to `var`
 - [x] check package's OS
 - [x] save package version to database of installed packages
 - [x] json config
 - [x] download and extract plugins to a directory named after the package name
 - [ ] clean up handling of folders and passing them between functions
 - [x] use static methods
 - [x] mark scripts as executable when installing
 - [x] delete empty parent folders when removing a package
 - [x] PKGINFO: OS, build for different OSes
 - [ ] install single `.dll` files (no full `lpc` archive)
 - [x] install plugin's LICENSE to `share/LICENSE/<plugin>`
 - [x] plugin name and DESCRIPTION in `apkg list-*`
 - [x] check LeoConsole version if plugin is compatible
 - [ ] make possible for package to install empty folder (like scripts folder)
 - [x] rename `repo` to `repos.txt`
 - [x] manifest extension: additional files download/folders creation declared in manifest
   - [X] documentation
 - [x] extension system (`share/apkg/extensions`)
 - [ ] `config` subcommand
 - [ ] include contrib repo in config.json as disabled for simple enabling
 - [x] extension alias in metadata (or generated automatically)
